# .github/workflows/build-windows.yml
name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas openpyxl
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name="RecipeManager" recipe_manager.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: RecipeManager-Windows
        path: dist/RecipeManager.exe
